//Variables
let edad = 67
let nombreUsuario = Bautista
let nombreUsuario2 = Marcos
let numero = 4
let edad2 = 42
let dia = "Viernes"
let contrasenia = "secreto"
let botonActividad1 = document.querySelector ("#BotonActividad1")
let parrafoActividad1 = document.querySelector ("#ParrafoActividad1")
let botonActividad2 = document.querySelector ("#BotonActividad2")
let parrafoActividad2 = document.querySelector ("#ParrafoActividad2")
let botonActividad3 = document.querySelector ("#BotonActividad3")
let parrafoActividad3 = document.querySelector ("#ParrafoActividad3")
let botonActividad4 = document.querySelector ("#BotonActividad4")
let parrafoActividad4 = document.querySelector ("#ParrafoActividad4")
let botonActividad5 = document.querySelector ("#BotonActividad5")
let parrafoActividad5 = document.querySelector ("#ParrafoActividad5")
let botonActividad6 = document.querySelector ("#BotonActividad6")
let parrafoActividad6 = document.querySelector ("#ParrafoActividad6")
let botonActividad7 = document.querySelector ("#BotonActividad7")
let parrafoActividad7 = document.querySelector ("#ParrafoActividad7")
